remote_theme: pmarsceill/just-the-docs
title: Prolog MSDF Tools
description: MSDF is a meta-language for modular specification of programming languages
repository: "pdmosses/prolog-msdf-tools"
# Aux links for the upper right navigation
aux_links:
  "prolog-msdf-tools on GitHub":
    - "//github.com/pdmosses/prolog-msdf-tools"
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
