remote_theme: pmarsceill/just-the-docs
title: Prolog MSOS Tool
description: MSDF is a meta-language for modular specification of programming languages
repository: "pdmosses/prolog-msos-tool"
# Aux links for the upper right navigation
aux_links:
  "prolog-msos-tool on GitHub":
    - "//github.com/pdmosses/prolog-msos-tool"
plugins:
    - jekyll-seo-tag
compress_html:
  blanklines: true
